package io.github.sanjuktadavuluri.shortener;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.fail;
import static org.junit.jupiter.api.Assumptions.assumeFalse;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;
import org.junit.jupiter.api.Test;
import org.springframework.context.ConfigurableApplicationContext;

/**
 * Ticket #187 (spec 0008): the committed {@code docs/api/openapi.yaml} equals what the code
 * generates, and the definition's content matches the public contract.
 */
class OpenApiDriftIT extends IntegrationTest {

  private static final String REGENERATE = "scripts/openapi.sh";

  @Test
  void theCommittedDefinitionEqualsTheGeneratedOne() throws Exception {
    assumeFalse(Boolean.getBoolean("openapi.write"), "regenerating");
    String generated = generate();
    String committed =
        Files.readString(OpenApiDefinitionIT.COMMITTED, StandardCharsets.UTF_8)
            .replace("\r\n", "\n");
    if (!generated.equals(committed)) {
      fail(
          "docs/api/openapi.yaml differs from the definition generated by the code."
              + " Regenerate it with: "
              + REGENERATE
              + "\n"
              + diff(committed, generated));
    }
  }

  @Test
  void theDefinitionHasExactlyTheThreePublicOperationsWithTheDocumentedStatuses() throws Exception {
    String yaml = generate();
    List<String> paths = new ArrayList<>();
    for (String line : yaml.split("\n")) {
      if (line.matches("  /\\S*:")) {
        paths.add(line.trim());
      }
    }
    assertThat(paths)
        .containsExactlyInAnyOrder("/links:", "/{short_code}:", "/links/{short_code}/stats:");
    assertThat(yaml).doesNotContain("actuator");

    assertThat(section(yaml, "  /links:")).contains("\"201\"", "\"400\"", "\"422\"", "\"503\"");
    assertThat(section(yaml, "  /{short_code}:")).contains("\"302\"", "\"404\"", "\"410\"");
    String stats = section(yaml, "  /links/{short_code}/stats:");
    assertThat(stats).contains("\"200\"", "\"404\"", "- bearerAuth");
    assertThat(section(yaml, "  /links:")).doesNotContain("bearerAuth");
    assertThat(section(yaml, "  /{short_code}:")).doesNotContain("bearerAuth");
  }

  @Test
  void noExampleLooksLikeARealTokenReferrerOrUserAgent() throws Exception {
    String yaml = generate();
    assertThat(yaml)
        .doesNotContainPattern("(?i)mozilla/|chrome/|safari/|curl/|user-agent: ")
        .doesNotContainPattern("(?i)https?://(www\\.)?(google|facebook|twitter|t\\.co|bing)\\.");
    Pattern longToken = Pattern.compile("(?i)example:\\s*['\"]?[A-Za-z0-9_-]{32,}");
    assertThat(longToken.matcher(yaml).find()).as("example resembling a real token").isFalse();
  }

  private static String section(String yaml, String header) {
    int start = yaml.indexOf("\n" + header + "\n");
    assertThat(start).as(header).isGreaterThanOrEqualTo(0);
    int next = yaml.indexOf("\n  /", start + header.length() + 2);
    int components = yaml.indexOf("\ncomponents:", start);
    int end = next > 0 ? next : components;
    return yaml.substring(start, end);
  }

  private static String diff(String committed, String generated) {
    String[] a = committed.split("\n", -1);
    String[] b = generated.split("\n", -1);
    StringBuilder out = new StringBuilder("--- committed\n+++ generated\n");
    int shown = 0;
    for (int i = 0; i < Math.max(a.length, b.length) && shown < 40; i++) {
      String x = i < a.length ? a[i] : null;
      String y = i < b.length ? b[i] : null;
      if (x == null ? y != null : !x.equals(y)) {
        out.append("@@ line ").append(i + 1).append("\n");
        if (x != null) out.append("- ").append(x).append("\n");
        if (y != null) out.append("+ ").append(y).append("\n");
        shown++;
      }
    }
    return out.toString();
  }

  private static String generate() throws Exception {
    try (ConfigurableApplicationContext app =
        TestApps.start(TestDatabases.newFile(), "--springdoc.api-docs.enabled=true")) {
      HttpResponse<String> response =
          HttpClient.newHttpClient()
              .send(
                  HttpRequest.newBuilder(
                          URI.create(
                              "http://localhost:" + TestApps.port(app) + "/v3/api-docs.yaml"))
                      .build(),
                  HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));
      assertThat(response.statusCode()).isEqualTo(200);
      String body = response.body().replace("\r\n", "\n");
      return body.endsWith("\n") ? body : body + "\n";
    }
  }
}
